name: ld29_beneath_the_surface
description: A sample dartemis application
dependencies:
  browser: any
  canvas_query: any
  dartemis_toolbox: any
  gamedev_helpers:
    git: https://github.com/denniskaselow/gamedev_helpers
  hop: any
  tweenengine: any
transformers:
- $dart2js:
    minify: true